mysite/blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
        path('', views.PostList.as_view(), name='home'),
        path('<slug:slug>/', views.post_detail, name='post_detail'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('miniurl/', include('miniurl.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('notebook', include('notebook.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/notebook/models.py
from django.db import models
from django.urls import reverse
from tinymce.models import HTMLField

COLORS = (
    ('a', 'yellow'),
    ('b', 'white'),
    ('c', 'green'),
    ('d', 'red'),
    ('e', 'blue')
)


class Tags(models.Model):
    title = models.CharField(unique=True, max_length=240)

    def __str__(self):
        return self.title

    def get_edit_url(self):
        return reverse('notes:tag_update', kwargs={'pk': self.id})

    def get_delete_url(self):
        return reverse('notes:tag_delete', kwargs={'pk': self.id})

    @staticmethod
    def filters_data(request, qs):
        q = request.GET.get('q', None)
        search_name = request.GET.get('search_name', None)

        qs = qs.filter(title__icontains=q) if q else qs
        qs = qs.filter(title__icontains=search_name) if search_name else qs

        return qs


class Note(models.Model):
    pinned = models.BooleanField(default=False, verbose_name='sticky_note')
    title = models.CharField(max_length=400)
    description = models.HTMLField(blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    date = models.DateField(blank=True, null=True)
    tag = models.ManyToManyField(Tags, blan=True)
    color = models.CharField(max_length=1, choices=COLORS, default='a')

    class Meta:
        ordering = ['-pinned', '-timestamp']

    def __str__(self):
        return self.title

    def get_edit_url(self):
        return reverse('notes:note_update', kwargs={'pk': self.id})

    def get_show_url(self):
        return reverse('notes:show_note', kwargs={'pk': self.id})

    @staticmethod
    def filters_data(request, qs):
        q = request.GET.get('q', None)
        tags = request.GET.getlist('tag', None)

        if tags:
            tags_ = Tags.objects.filter(id__in=tags)
            qs = qs.filter(tag__in=tags_)

        qs = qs.filter(title__icontains=q) if q else qs

        return qs

mysite/notebook/forms.py
from django import forms
from .models import Tags, Note


class BaseForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class NoteForm(BaseForm, forms.ModelForm):
    class Meta:
        model = Note
        fields = ['pinned', 'color', 'title', 'tag', 'description']


class TagForm(BaseForm, forms.ModelForm):
    class Meta:
        model = Tags
        fields = '__all__'

mysite/notebook/views.py
from django.shortcuts import reverse, redirect, get_object_or_404, HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, DetailView, CreateView
from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages

from django_tables2 import RequestConfig

from .models import Tags, Note
from .forms import NoteForm, TagForm
from .table import TagsTable


@method_decorator(staff_member_required, name='dispatch')
class NoteHomepageView(ListView):
    template_name = 'notes/homepage.html'
    model = Note

    def get_queryset(self):
        qs = Note.objects.all()
        qs = Note.filters_data(self.request, qs)

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_form'] = NoteForm()
        context['pinned_qs'] = self.object_list.filter(pinned=True)
        context['qs'] = self.object_list.filter(pinned=False)[:30]

        return context

mysite/notebook/templates/notes/form.html
{% extends 'dashboard.html' %}  {% load render_table from django_tables2 %}

{% block extra_css %}
 {{ form.media }}
 <style>
    textarea.form-control{
        max-height: 600px;
        width:1800px;
    }
    #id_description {
        max-height: 600px;
        height:600px;
    }
    #id_tag {
        max-height: 250px;
        height:250px;
    }
 </style>
 {% endblock %}

{% block content %}
    <div class="content">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <div class='card'>
                    <div class='card-header'>
                        <h4>{{form_title}}</h4>
                        <!-- Large modal -->
                        <a href="{{ back_url }}" class="btn btn-warining pull-right">Back</a>
                    </div>
                     <div class="card-body">
                        <form method='post' class='form'>
                            {% csrf_token %}
                            {{ form }}
                            <br />
                            <button class='btn btn-success pull-right' type='submit'><i class='fa fa-save'></i></button> 
                        </form>
                     </card>
                    
                </div>
            </div>
            <div class="col-2"></div>
        </div>


        </div>

    </div>

{% endblock %}

mysite/notebook/templates/notes/homepage.html
{% extends 'dashboard.html' %}  {% load render_table from django_tables2 %}

{% block extra_css %}
    {{ create_form.media }}
    <style>
        textarea.form-control {
            max-height: 600px;
            width:1800px;
        }
        #id_description {
            max-height: 500px;
            height:500px;
        }
        #id_description_ifr {
            max-height: 500px;
            height:500px;
        }
        #id_tag {
            max-height: 150px;
            height:150px;
        }
    </style>
 
{% endblock %}

{% block content %}
    <div class="content">
        <div class="row">
            <div class="col-12">
                <div class='card'>
                    <div class='card-header'>
                        <h4>Notes</h4>

                    </div>
                    <div class='card-body'>
                        <div class='row'>
                            <div class='col-6'>
                            <!-- Large modal -->
                                <button type="button" class="btn btn-success" data-toggle="modal" data-target=".bd-example-modal-lg">New Note</button>
                                <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                                <div class="modal-dialog modal-lg">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Create</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body" style='height:700px; overflow-y: scroll;'>
                                             <form method='post' class='form' action='{% url "notes:validate_note_creation" %}'>
                                                {% csrf_token %}
                                                {{ create_form }}
                                                <br />
                                            <button type='submit' class='btn btn-primary'><i class='fa fa-save'></i> Save</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                        </div></div>
                            <div class='col-6'>
                                <form method='get'>
                                    <input name='q' class='form-control' type='text' placeholder='Search' />
                                    <button type='submit' class='btn btn-info'><i class='fa fa-search'> </i> </button>
                                    <a href='{{ request.path }}' style='color:red' class='pull-right btn btn-warning'><i class='fa fa-remove'> </i></a>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class='row notes'> 
            <div class='col-12'><h5> Pinned </h5></div>
            {% for note in pinned_qs %}
                {% include 'notes/note_card.html' %}
            {% endfor %}
        </div>

        <div class='row notes'> 
            <div class='col-12'><h5> Rest notes </h5></div>
            {% for note in qs %}
                {% include 'notes/note_card.html' %}
            {% endfor %}
        </div>
    </div>

{% endblock %}

mysite/notebook/templates/notes/note_card.html
<div class='col-3'>
    <div class="card card-nav-tabs text-center" style=' border-top: 5px solid {{ note.get_color_display }};'>
        <div class="card-header card-header-primary">
            {% if note.pinned %}
                <a style='color:green' href="{% url 'notes:pinned' note.id %}"><i style='color:green' class='fa fa-thumb-tack'></i></a>
            {% else %}
                <a href="{% url 'notes:pinned' note.id %}"><i style='color:red' class='fa fa-thumb-tack'></i></a>
            {% endif %}
        </div>
        <div class="card-body">
            <h4 class="card-title">{{ note|safe }}</h4>
            <p class="card-text">{{ note.description|safe|truncatechars_html:50 }}</p>
        </div>
        <div class="card-footer text-muted">
            {% for tag in note.tag.all %} <a href='{{ request.path }}?tag={{ tag.id }}'><i class="fa fa-tag" aria-hidden="true"></i> {{ tag }}</a>  {% empty %} No tags{% endfor %}
            <br>
            <p class='text-muted'>Created {{ note.timestamp}} <p>
            <a href='{{ note.get_edit_url }}' style='color:blue' class='pull-left'><i class='fa fa-edit'> </i></a>
            <a onclick='return confirm("Εισαι σιγουρος;")' href='{% url "notes:delete_note" note.id %}' style='color:red' class='pull-right'><i class='fa fa-trash'> </i></a>
        </div>
    </div>
</div>